// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTWpAtvy7AZ0Xun08YUZHDg-p5IjDQCqA',
    appId: '1:315852449270:web:5c9d7862af1461186e13d7',
    messagingSenderId: '315852449270',
    projectId: 'notepadwithcheck',
    authDomain: 'notepadwithcheck.firebaseapp.com',
    storageBucket: 'notepadwithcheck.appspot.com',
    measurementId: 'G-HBK90B07KS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkN4fuIp55yGDw2OcbiWtBKdUZD37n8uQ',
    appId: '1:315852449270:android:02970e06bf633c016e13d7',
    messagingSenderId: '315852449270',
    projectId: 'notepadwithcheck',
    storageBucket: 'notepadwithcheck.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFZsbju13pOmwpvF2VNeqDx69iupTjHgw',
    appId: '1:315852449270:ios:6eb79b3cc82136db6e13d7',
    messagingSenderId: '315852449270',
    projectId: 'notepadwithcheck',
    storageBucket: 'notepadwithcheck.appspot.com',
    iosBundleId: 'com.example.flutterkeepme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFZsbju13pOmwpvF2VNeqDx69iupTjHgw',
    appId: '1:315852449270:ios:6eb79b3cc82136db6e13d7',
    messagingSenderId: '315852449270',
    projectId: 'notepadwithcheck',
    storageBucket: 'notepadwithcheck.appspot.com',
    iosBundleId: 'com.example.flutterkeepme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTWpAtvy7AZ0Xun08YUZHDg-p5IjDQCqA',
    appId: '1:315852449270:web:251a6393f5ba86466e13d7',
    messagingSenderId: '315852449270',
    projectId: 'notepadwithcheck',
    authDomain: 'notepadwithcheck.firebaseapp.com',
    storageBucket: 'notepadwithcheck.appspot.com',
    measurementId: 'G-HJ65RQN8Q4',
  );

}